### PR TITLE
update tests for case change

### PR DESCRIPTION
**Pull request by Jarrio**

### CODE REVIEW

**Comment by ianharrigan** [comment]
can we revert the changes in the HttpServerBase.hx? I dont think they are needed and are just style changes (like tabs, not spaces)... so its just noise

**Comment by Jarrio** [comment]
gaah, i have formatter auto on and it just did that by itself :/ I'll have to revisit the file later

**Comment by ianharrigan** [comment]
Cant you just revert it? I dont _think_ there are any relevant changes are there?

**Comment by Jarrio** [comment]
I saw the case at 164 in a find and replace

**Comment by ianharrigan** [comment]
Ah you are right, yeah, there are changes there... 👍

**Comment by Jarrio** [comment]
ahh you were right. It looks like you toLowerCase the method anyway so these values can actually just remain as they were

**Pull request merged**
